# Generated by Django 5.2.16 on 2026-07-29 19:28

import accounts.managers
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('role', models.CharField(choices=[('JEUNE', 'Jeune (Routier)'), ('CC', 'Coordinateur de Communauté'), ('CG', 'Chef de Groupe')], max_length=10)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('ACTIF', 'Actif'), ('REFUSE', 'Refusé'), ('SUSPENDU', 'Suspendu')], default='EN_ATTENTE', max_length=20)),
                ('nom', models.CharField(max_length=80)),
                ('prenoms', models.CharField(max_length=120)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('AUTRE', 'Autre')], max_length=10)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('valide_le', models.DateTimeField(blank=True, null=True)),
                ('auth_provider', models.CharField(choices=[('LOCAL', 'Local'), ('GOOGLE', 'Google'), ('TIKTOK', 'TikTok')], default='LOCAL', max_length=20)),
                ('oauth_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('communaute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='organization.communaute')),
            ],
            options={
                'ordering': ['nom', 'prenoms'],
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
    ]
