# Generated by Django 5.2.16 on 2026-08-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='etape_placee_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
