# Generated by Django 5.2.16 on 2026-08-30 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=160)),
                ('duree_minutes', models.PositiveSmallIntegerField()),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('OUVERTE', 'Ouverte'), ('CLOTUREE', 'Clôturée')], default='BROUILLON', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('communaute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='organization.communaute')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('score_max', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('present', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='evaluations.evaluation')),
                ('jeune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('evaluation', 'jeune')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('QCM', 'QCM'), ('TEXTE_TROUS', 'Texte à trous'), ('REPONSE_DIRECTE', 'Réponse directe')], max_length=20)),
                ('enonce', models.TextField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('reponse_attendue', models.JSONField()),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('ordre', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='evaluations.evaluation')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.JSONField()),
                ('est_correcte', models.BooleanField(blank=True, null=True)),
                ('points_obtenus', models.PositiveSmallIntegerField(default=0)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='evaluations.evaluationattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='evaluations.evaluationquestion')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
