# Generated by Django 5.2.16 on 2026-07-29 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScarfState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moities_perdues', models.PositiveSmallIntegerField(default=0)),
                ('recovery_at', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jeune', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foulard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'état foulard',
                'verbose_name_plural': 'états foulard',
            },
        ),
    ]
