# Generated by Django 5.2.16 on 2026-07-29 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('NOVICIAT', 'Noviciat'), ('APPRENTISSAGE', 'Apprentissage'), ('COMPAGNONNAGE', 'Compagnonnage'), ('DEPART_ROUTIER', 'Départ Routier')], max_length=30)),
                ('ordre', models.PositiveSmallIntegerField()),
                ('titre', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('couleur_brevet', models.CharField(max_length=20)),
                ('modele_brevet', models.CharField(blank=True, max_length=255)),
                ('nb_questions_parcours', models.PositiveSmallIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('communaute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='organization.communaute')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ordre'],
                'unique_together': {('communaute', 'code'), ('communaute', 'ordre')},
            },
        ),
    ]
