# Generated by Django 5.2.16 on 2026-07-29 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('QCM', 'QCM'), ('TEXTE_TROUS', 'Texte à trous'), ('REPONSE_DIRECTE', 'Réponse directe')], max_length=20)),
                ('enonce', models.TextField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('reponse_attendue', models.JSONField()),
                ('explication', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_creees', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='formation.stage')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('nom_affiche', models.CharField(max_length=200)),
                ('fichier', models.FileField(blank=True, upload_to='brevets/')),
                ('couleur', models.CharField(max_length=20)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('jeune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brevets', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brevets', to='formation.stage')),
            ],
            options={
                'ordering': ['-delivered_at'],
                'unique_together': {('jeune', 'stage')},
            },
        ),
        migrations.CreateModel(
            name='FormationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('VALIDE', 'Validé'), ('VERROUILLE', 'Verrouillé')], default='EN_COURS', max_length=20)),
                ('nb_reussies', models.PositiveSmallIntegerField(default=0)),
                ('nb_total', models.PositiveSmallIntegerField(default=0)),
                ('reponses', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('jeune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='formation.stage')),
            ],
            options={
                'ordering': ['stage__ordre'],
                'unique_together': {('jeune', 'stage')},
            },
        ),
    ]
