# Generated by Django 5.2.16 on 2026-08-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_question_certificate_formationprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formationprogress',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('VALIDE', 'Validé'), ('ACQUIS', 'Acquis (placement)'), ('VERROUILLE', 'Verrouillé')], default='EN_COURS', max_length=20),
        ),
    ]
