# Generated by Django 5.2.6 on 2026-08-31 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=160)),
                ('duree_jours', models.PositiveSmallIntegerField(default=2)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('OUVERTE', 'Ouverte'), ('CLOTUREE', 'Clôturée')], default='BROUILLON', max_length=20)),
                ('partage_token', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('communaute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='organization.communaute')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='competitions.competition')),
                ('jeune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', 'updated_at'],
                'unique_together': {('competition', 'jeune')},
            },
        ),
        migrations.CreateModel(
            name='CompetitionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('QCM', 'QCM'), ('TEXTE_TROUS', 'Texte à trous'), ('REPONSE_DIRECTE', 'Réponse directe')], max_length=20)),
                ('enonce', models.TextField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('reponse_attendue', models.JSONField()),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('ordre', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='competitions.competition')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.JSONField()),
                ('est_correcte', models.BooleanField(default=False)),
                ('points_obtenus', models.PositiveSmallIntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='competitions.competitionattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='competitions.competitionquestion')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
